openapi: 3.0.3
info:
  title: design
  description: |-
    | **Name** | **Detail** |
    | --- | --- |
    |  |  |
  version: 1.0.0
  contact: {}
servers:
  - url: '{{XXX}}'
paths:
  /products/{id}:
    get:
      summary: Get product detail
      description: Get product detail
      operationId: getProductDetail
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  name:
                    type: string
                    example: Product 1
              examples:
                Success:
                  value:
                    id: 1
                    name: Product 1
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
              examples:
                Not found:
                  value:
                    message: Product not found
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error
              examples:
                Error:
                  value:
                    message: Error
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: ''
tags: []
